### ISSUE TITLE
Xcode Project file

### ISSUE THREAD

**Issue by diffractometer** [burgalon/react-native-redux-navigator#1]
Hey!

Do you have a an xcode project with this?

**Comment by burgalon** [comment]
You mean an example?

**Comment by diffractometer** [comment]
Yes.

**Comment by burgalon** [comment]
I'll try to publish something later today

**Comment by diffractometer** [comment]
Cool thx!

**Comment by burgalon** [comment]
Hey @diffractometer 
I pushed (an example)[https://github.com/burgalon/react-native-redux-navigator/tree/master/examples/ReactRativeReduxNavigatorExample]
You will need to move the directory out of the `react-native-redux-navigator` and then copy the `src` in order for it to work as I wasn't able to get to the bottom of why the `npm run-script start` is failing and how to create the dependency two level up.

**Comment by diffractometer** [comment]
Awesome thanks for doing it will check out shortly!

**Comment by diffractometer** [comment]
I'm getting the error when I try to `npm start` from ReactRativeReduxNavigatorExample at the deepest level of the repo is this what you're talking about?

```
> ReactRativeReduxNavigatorExample@0.0.1 start /Users/hunterhusar/dev/trinity/react-native-redux-navigator/examples/ReactRativeReduxNavigatorExample
> node_modules/react-native/packager/packager.sh

/Users/hunterhusar/dev/trinity/react-native-redux-navigator/examples/ReactRativeReduxNavigatorExample/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126
      if (!option) this.log.error("Unknown option: " + alias + "." + key, ReferenceError);
                           ^

TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (/Users/hunterhusar/dev/trinity/react-native-redux-navigator/examples/ReactRativeReduxNavigatorExample/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:28)
    at OptionManager.addConfig (/Users/hunterhusar/dev/trinity/react-native-redux-navigator/examples/ReactRativeReduxNavigatorExample/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/hunterhusar/dev/trinity/react-native-redux-navigator/examples/ReactRativeReduxNavigatorExample/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/hunterhusar/dev/trinity/react-native-redux-navigator/examples/ReactRativeReduxNavigatorExample/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at compile (/Users/hunterhusar/dev/trinity/react-native-redux-navigator/examples/ReactRativeReduxNavigatorExample/node_modules/react-native/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/Users/hunterhusar/dev/trinity/react-native-redux-navigator/examples/ReactRativeReduxNavigatorExample/node_modules/react-native/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hunterhusar/dev/trinity/react-native-redux-navigator/examples/ReactRativeReduxNavigatorExample/node_modules/react-native/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/4.2.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.1
npm ERR! npm  v2.13.5
npm ERR! code ELIFECYCLE
npm ERR! ReactRativeReduxNavigatorExample@0.0.1 start: `node_modules/react-native/packager/packager.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ReactRativeReduxNavigatorExample@0.0.1 start script 'node_modules/react-native/packager/packager.sh'.
npm ERR! This is most likely a problem with the ReactRativeReduxNavigatorExample package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/react-native/packager/packager.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls ReactRativeReduxNavigatorExample
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hunterhusar/dev/trinity/react-native-redux-navigator/examples/ReactRativeReduxNavigatorExample/npm-debug.lo
```

**Comment by burgalon** [comment]
Yep. Exactly this. If you move the example directory out - it will work

**Comment by diffractometer** [comment]
Cool. 

I don't understand your directions. Do you mean copy everything inside of the src/ directory into the src/ directory of the example app?

**Comment by burgalon** [comment]
@diffractometer fixed it now

**Comment by bartonhammond** [comment]
Assuming from your comment above of "fixed it now", no directory or copying of files is required.  If so, this is the error I am getting with ```npm start```

```
~/projects/MFV/react-native-redux-navigator/examples/ReactRativeReduxNavigatorExample (master)$ npm start

> ReactRativeReduxNavigatorExample@0.0.1 start /Users/barton/projects/MFV/react-native-redux-navigator/examples/ReactRativeReduxNavigatorExample
> node_modules/react-native/packager/packager.sh

module.js:339
    throw err;
    ^

Error: Cannot find module 'figures'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/barton/projects/MFV/react-native-redux-navigator/examples/ReactRativeReduxNavigatorExample/node_modules/react-native/node_modules/yeoman-environment/node_modules/inquirer/lib/objects/separator.js:3:15)
    at Module._compile (module.js:435:26)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/barton/projects/MFV/react-native-redux-navigator/examples/ReactRativeReduxNavigatorExample/node_modules/react-native/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! ReactRativeReduxNavigatorExample@0.0.1 start: `node_modules/react-native/packager/packager.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ReactRativeReduxNavigatorExample@0.0.1 start script 'node_modules/react-native/packager/packager.sh'.
npm ERR! This is most likely a problem with the ReactRativeReduxNavigatorExample package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/react-native/packager/packager.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls ReactRativeReduxNavigatorExample
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/barton/projects/MFV/react-native-redux-navigator/examples/ReactRativeReduxNavigatorExample/npm-debug.log

```

**Comment by burgalon** [comment]
Hey @bartonhammond  - figures is indeed a dependency of `inquirer` which is a dendenchy of `yeoman-environment` which is a dependency of `react-native`. 
Could you try to upgrade your `npm` to 3.4.0, delete the node_modules directory in ReactRativeReduxNavigatorExample and run npm install in the example directory again?
